// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjAkU8PBROu0XiEUHXgnHutc3vR-6Un8',
    appId: '1:973883413065:web:8691b52dfcc20a561f6598',
    messagingSenderId: '973883413065',
    projectId: 'todo-ntd612005',
    authDomain: 'todo-ntd612005.firebaseapp.com',
    storageBucket: 'todo-ntd612005.firebasestorage.app',
    measurementId: 'G-2W3EVZLQQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jaTiOp1glzgWDobGegHRgTI013OZO0A',
    appId: '1:973883413065:android:235d4c3c3dff16991f6598',
    messagingSenderId: '973883413065',
    projectId: 'todo-ntd612005',
    storageBucket: 'todo-ntd612005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComJ2ZxitZUxEAKD7BbRhKf0MNTsZRlGE',
    appId: '1:973883413065:ios:73528b95fe0731a81f6598',
    messagingSenderId: '973883413065',
    projectId: 'todo-ntd612005',
    storageBucket: 'todo-ntd612005.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyComJ2ZxitZUxEAKD7BbRhKf0MNTsZRlGE',
    appId: '1:973883413065:ios:73528b95fe0731a81f6598',
    messagingSenderId: '973883413065',
    projectId: 'todo-ntd612005',
    storageBucket: 'todo-ntd612005.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZjAkU8PBROu0XiEUHXgnHutc3vR-6Un8',
    appId: '1:973883413065:web:aab657eca5eaf0dd1f6598',
    messagingSenderId: '973883413065',
    projectId: 'todo-ntd612005',
    authDomain: 'todo-ntd612005.firebaseapp.com',
    storageBucket: 'todo-ntd612005.firebasestorage.app',
    measurementId: 'G-FHT86ZGRB5',
  );
}
